### ISSUE TITLE
dzMin2 indexing in managelayers

### ISSUE THREAD

**Issue by chadagreene** [alex-s-gardner/GEMB#5]
This issue is to be addressed in the ISSM version of GEMB.

> @alex-s-gardner I've made a few edits to `managelayers`. Most of the edits have been for efficiency and readability, and have not impacted the output of the function. However, the new edit on line [99](https://github.com/alex-s-gardner/GEMB/blob/29eb9cdfa41fe6d7c2b795a6dcd2bf37589a3925/GEMB/managelayers.m#L99) _does_ impact the output of `managelayers` and the `GEMB` function. 
> 
> Can you confirm that the change I made on line 99 is correct or if I should revert it?
> 
> _Originally posted by @chadagreene in https://github.com/alex-s-gardner/GEMB/issues/1#issuecomment-2226747273_

**Comment by NJSchlegel** [comment]
To be implemented in ISSM C++.

**Comment by NJSchlegel** [comment]
I think the best thing to do is to create dzMin2 and dzMax2 together, before changing any of the layers. Then, make sure to delete the dzMax2 elements after the merging of small layers, just like dzMin2 elements are now deleted.  Then, split the cells that are too large, without doing another loop to determine dzMax2 (since it is already calculated).  This has been implemented in GEMB matlab ([pull request 27](https://github.com/alex-s-gardner/GEMB/pull/27)) and in ISSM, and pushed.  The dzMin2 and dzMax2 loops were also parallelized in matlab and this version is benchmarked against results from testGEMBISSM with the new mat files pushed.

**Comment by NJSchlegel** [comment]
This issue has been pushed to the ISSM main. [commit e068d33](https://github.com/ISSMteam/ISSM/commit/e068d33f28a8b19d599f85531321675112b2f51e)
